CREATE TABLE users (
       id BIGINT NOT NULL AUTO_INCREMENT,
       username VARCHAR(50) NOT NULL UNIQUE,
       email VARCHAR(100) NOT NULL UNIQUE,
       password VARCHAR(255) NOT NULL,
       role VARCHAR(50) NOT NULL DEFAULT 'ROLE_USER',
       PRIMARY KEY (id)
);