spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/kiritsu_auth?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 9000